koloristika/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings
from users.views import profile_view

urlpatterns = [
    path("", include("main.urls", namespace='main')),
    path("services/", include("services.urls", namespace='services')),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
    path('accounts/', include('allauth.urls')),
    path("profile/", profile_view, name="account_profile"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path


from . import views
from services import views as serv_views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('prices/', serv_views.product_price, name='price'),
    path('prices/page/<int:page>/', serv_views.product_price, name='price_paginated'),
]

services/urls.py
from django.urls import path


from . import views

app_name = 'services'

urlpatterns = [
    path('', views.services, name='index'),
    path('<slug:slug>/', views.service_detail, name='service'),
    path('<slug:category_slug>/<slug:product_slug>', views.product_detail, name='product'),
]

main/models.py
from django.db import models

class SliderContent(models.Model):
    content = models.TextField(
        verbose_name='Описание контента'
    )
    slider_photo = models.ImageField(
        upload_to='slider-info/', verbose_name='Фото на слайдере'
    )
    link = models.URLField(
        blank=True, null=True, verbose_name='Ссылка на мероприятие'
    )

    class Meta:
        db_table = 'slider_content'
        verbose_name = 'слайдера'
        verbose_name_plural = 'слайдеры'
        ordering = ['id']

    def __str__(self):
        return 'Контент слайдера'

main/views.py
from django.shortcuts import render
from django.http import HttpResponse

from services.models import Categories, Masters, Products
from main.models  import SliderContent

# Create your views here.
def index(request):

    categories = Categories.objects.all()
    procedures = Products.objects.filter(show_on_homepage=True)[:4]
    slides = SliderContent.objects.all()

    context = {
        'title': 'Koloristika - Главная страница',
        'categories': categories,
        'procedures': procedures,
        'slides': slides,
    }

    return render(request, 'main/index.html', context)

def about(request):

    masters = Masters.objects.all()

    context = {
        'title': 'Koloristika - О нас',
        'masters': masters,
    }

    return render(request, 'main/about.html', context)

templates/main/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ title }}
{% endblock title %}




{% block content %}
<div class="ftco-blocks-cover-1">

  <div class="ftco-cover-1 d-flex align-items-center justify-content-center" style="background-image: url('{% static "images/hero_1.jpg" %}');">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <div class="box-92819">
            <p style='font-size: 30px; color: white;'>Более <span style="color: #43ab92;">1000</span> клиентов работают с нами постоянно на протяжении <span style="color: #43ab92;">10 лет!</span></a></p>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>


<div class="site-section">
  <div class="container">

    <div class="row align-items-stretch">
      <div class="col-lg-4">
        <div class="h-100 bg-white box-29291">
          <h2 class="heading-39291">Добро пожаловать <br>В салон <span style="color: #43ab92;">KOLORISTIKA</span></h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo mollitia id ea ab in! Nam eligendi distinctio, vitae.</p>
          <p>Alias odit ipsam quas unde obcaecati molestiae consequatur numquam cupiditate perferendis facere, nulla nemo id, accusantium corrupti tempora.</p>

          <p class="mt-5">
            <span class="d-block font-weight-bold text-black">Маслова Дарья</span>
            <span class="d-block font-weight-bold text-muted">Основатель, Топ-мастер</span>
            
            <img src="{% static "images/signature.svg" %}" alt="Image" class="img-fluid" width="140">
          </p>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="owl-carousel owl-3">
          <img src="{% static "images/about_1.jpg" %}" alt="Image" class="img-fluid">
          <img src="{% static "images/about_2.jpg" %}" alt="Image" class="img-fluid">
          <img src="{% static "images/about_3.jpg" %}" alt="Image" class="img-fluid">
        </div>
      </div>
    </div>

  </div>
</div>


<div class="site-section">
<div class="container">

  <div class="row justify-content-center text-center mb-5 section-2-title">
    <div class="col-md-8">
      <h2 class="heading-39291">Наша команда</h2>
      <p>Команда <span style="color: #43ab92;">KOLORISTIKA</span> — это мастера красоты и стиля. Мы создаем индивидуальные образы, подчеркивая естественную красоту и особенности каждого клиента.<br>Наши стилисты используют современные техники ухода и окрашивания, чтобы вы выглядели безупречно.</p>
    </div>
  </div>

  <div class="row align-items-stretch">

    {% for master in masters %}
      <div class="col-lg-4 col-md-6 mb-5">
        <div class="post-entry-1 h-100 bg-white text-center">
          <a href="#" class="d-inline-block">
            <img src="{{ master.photo.url }}" alt="Image"
            class="img-fluid">
          </a>
          <div class="post-entry-1-contents">
            <span class="meta">{{ master.level }}</span>
            <h2>{{ master.name }}</h2>
            <p>{{ master.description }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
    
  </div>
  
</div>
</div>
{% endblock content %}

templates/main/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block content %}
<div class="owl-carousel-wrapper">    
  <div class="box-92819">
    <div class="owl-carousel slide-one-item-alt-text">

      {% for slide in slides %}
        <div>
        <h1 class="mb-3">{{ slide.content|safe }}</span></h1>
          <p class="mb-0"><a href="{{ slide.link }}" class="btn btn-primary rounded-0">Подробнее</a></p>
        </div>
      {% endfor %}

      <div>
        <h1 class="text-uppercase mb-3">Добро пожаловать в <span style="color: #43ab92;">koloristika</span></h1>
        <p class="mb-5">Стиль, уход и профессионализм. Мы создаем образы, подчеркивающие вашу индивидуальность</p>
        <p class="mb-0"><a href="#" class="btn btn-primary rounded-0">Подробнее</a></p>
      </div>

    </div>
  </div>

  <div class="owl-carousel owl-1 ">
    {% for slide in slides %}      
      <div class="ftco-cover-1" style="background-image: url('{{ slide.slider_photo.url }}')"></div>
    {% endfor %}  
  </div>
</div>


<!-- Услуги -->
<div class="site-section">
  <div class="container">

    <div class="row mb-5 align-items-center">
      <div class="col-md-7">
        <h2 class="heading-39291 mb-0">Наши услуги</h2>
      </div>
      <div class="col-md-5 text-right">
      </div>
    </div>
    <div class="row">

      {% for category in categories %}
        <div class="col-md-6 mb-4 col-lg-4" data-aos="fade-up" data-aos-delay="{{ forloop.counter0|divisibleby:3|yesno:'0,100,200' }}">
          <div class="service-29193 text-center">
            <span class="img-wrap mb-5">
              <img src="{% static category.svg_image %}" alt="{{ category.name }}" class="">
            </span>
            <h3 class="category-name mb-4"><a href="{% url 'services:service' category.slug%}">{{ category.name }}</a></h3>
            <p>{{ category.description }}</p>
          </div>
        </div>
      {% endfor %}
      
    </div>

  </div>
</div>
<!-- /Услуги -->


<!-- Проекты -->
  <!-- Должна быть возможность перейти на каждый проект и посмотреть информацию о нем -->
  <!-- Также возможность добавить новые проекты, всего возможно отображение последних 4х -->
<div class="site-section">
  <div class="container">
    <div class="row mb-5 align-items-center">
      <div class="col-md-7">
        <h2 class="heading-39291 mb-0">Топ процедур</h2>
      </div>
      <div class="col-md-5 text-right">
        <p class="mb-0"><a href="{% url 'main:price' %}" class="more-39291 {% if '/prices/' in request.path %}active{% endif %}">Все процедуры</a></p>
      </div>
    </div>

    <div class="row">
      {% for procedure in procedures %}
        <div class="col-lg-6">
            <div class="media-02819">
                <a href="{{ procedure.get_absolute_url }}" class="img-link">
                    <img src="{{ procedure.image.url }}" alt="{{ procedure.name }}" class="img-fluid">
                </a>
                <h3><a href="{{ procedure.get_absolute_url }}">{{ procedure.name }}</a></h3>
                <span>{{ procedure.category }}</span>
            </div>
        </div>
      {% endfor %}

    </div>
  </div>
</div>
<!-- /Проекты -->


<!-- Отзывы -->
  <!-- Посмотреть возможность добавить на сайт последние отзывы с яндекс карт -->
<div class="site-section section-4">
  <div class="container">

    <div class="row justify-content-center text-center">
      <div class="col-md-7">
        <div class="slide-one-item owl-carousel">
          <blockquote class="testimonial-1">
            <span class="quote quote-icon-wrap"><span class="icon-format_quote"></span></span>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus totam sit delectus earum facere ex ea sunt, eos?</p>
            <cite><span class="text-black">Mike Dorney</span> &mdash; <span class="text-muted">CEO and Co-Founder</span></cite>
          </blockquote>

          <blockquote class="testimonial-1">
            <span class="quote quote-icon-wrap"><span class="icon-format_quote"></span></span>
            <p>Eligendi earum ad perferendis dolores, dolor quas. Ullam in, eaque mollitia suscipit id aspernatur rerum! Sit quibusdam ullam tempora quis, in voluptatum maiores veritatis recusandae!</p>
            <cite><span class="text-black">James Smith</span> &mdash; <span class="text-muted">CEO and Co-Founder</span></cite>
          </blockquote>

          <blockquote class="testimonial-1">
            <span class="quote quote-icon-wrap"><span class="icon-format_quote"></span></span>
            <p> Officia, eius omnis rem non quis eos excepturi cumque sequi pariatur eaque quasi nihil dicta tempore voluptate culpa, veritatis incidunt voluptatibus qui?</p>
            <cite><span class="text-black">Mike Dorney</span> &mdash; <span class="text-muted">CEO and Co-Founder</span></cite>
          </blockquote>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Отзывы -->


{% endblock content %}