koloristika/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings
from users.views import profile_view

urlpatterns = [
    path("", include("main.urls", namespace='main')),
    path("services/", include("services.urls", namespace='services')),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
    path('accounts/', include('allauth.urls')),
    path("profile/", profile_view, name="account_profile"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path


from . import views
from services import views as serv_views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('prices/', serv_views.product_price, name='price'),
    path('prices/page/<int:page>/', serv_views.product_price, name='price_paginated'),
]

newsletter/urls.py
from django.urls import path

from . import views

app_name = 'newsletter'

urlpatterns = [
    path('subscribe/', views.subscribe, name='subscribe'),
    path('create/', views.create_newsletter, name='create_newsletter'),
    path('list/', views.newsletter_list, name='newsletter_list'),
    path('preview/<int:newsletter_id>/', views.preview_newsletter, name='preview_newsletter'),
    path('edit/<int:newsletter_id>/', views.edit_newsletter, name='edit_newsletter'), 
    path('delete/<int:newsletter_id>/', views.delete_newsletter, name='delete_newsletter'), 
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <title>
    {% block title %}
      {{ title }}
    {% endblock title %}
  </title>
  <meta charset="utf-8">
  <meta name="csrf-token" content="{{ csrf_token }}">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=DM+Sans:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static "fonts/icomoon/style.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.min.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery.fancybox.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "fonts/flaticon/font/flaticon.css" %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static "css/aos.css" %}">

    {% block extracss %}
    
    {% endblock extracss %}

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static "css/style.css" %}">

  </head>

  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

    
    <div class="site-wrap" id="home-section">

      <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
          <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
          </div>
        </div>
        <div class="site-mobile-menu-body"></div>
      </div>



      <header class="site-navbar site-navbar-target bg-white" role="banner">

        <div class="container-sm">
          <div class="row align-items-center position-relative">

            <div class="col-lg-4">
              <nav class="site-navigation text-right ml-auto " role="navigation">
                <ul class="site-menu main-menu js-clone-nav ml-auto d-none d-lg-block">
                  <li><a href="{% url 'services:index' %}" class="nav-link">Услуги</a></li>
                  <li><a href="{% url 'main:price' %}" class="nav-link">Прайс</a></li>
                  <li><a href="services.html" class="nav-link">Сертификат</a></li>
                </ul>
              </nav>
            </div>
            <div class="col-lg-4 text-center">
              <div class="site-logo">
                <a href="{% url 'main:index' %}">KOLORISTIKA</a>
              </div>


              <div class="ml-auto toggle-button d-inline-block d-lg-none"><a href="#" class="site-menu-toggle py-5 js-menu-toggle text-white"><span class="icon-menu h3 text-primary"></span></a></div>
            </div>
            <div class="col-lg-4">
              <nav class="site-navigation text-left mr-auto " role="navigation">
                <ul class="site-menu main-menu js-clone-nav ml-auto d-none d-lg-block">
                  <li><a href="{% url 'main:about' %}" class="nav-link">О нас</a></li>
                  <li><a href="blog.html" class="nav-link">Блог</a></li>
                  <li><a href="contact.html" class="nav-link">Контакты</a></li>
                  {% if user.is_authenticated %}
                    <li class="profile-link"><a href="{% url 'account_profile' %}" class="nav-link">Профиль</a></li>
                    <li class="profile-link"><a href="{% url 'account_logout' %}" class="nav-link">Выйти</a></li>
                  {% else %}
                    <li class="profile-link"><a href="{% url 'account_login' %}" class="nav-link">Войти</a></li>
                    <li class="profile-link"><a href="{% url 'account_signup' %}" class="nav-link">Регистрация</a></li>
                  {% endif %}
                </ul>
              </nav>
            </div>
            

          </div>
        </div>

      </header>

      {% block content %}
        
      {% endblock content %}    

    
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <div class="row">
              <div class="col-md-4 ml-auto">
                <h2 class="footer-heading mb-4" style="color: #43ab92; font-size: 22px;">KOLORISTIKA</h2>
                <ul class="list-unstyled">
                  <li><a href="{% url 'main:about' %}">+7(910)999-99-99</a></li>
                  <li><a href="#">+7(910)111-11-11</a></li>
                  <li><a href="#">testmail@gmail.com</a></li>
                  <li><a href="#">Деловая ул., 20, Нижний Новгород</a></li>
                  <li><a href="#">Пользовательское соглашение</a></li>
                </ul>
              </div>
              <div class="col-md-4 ml-auto">
                <h2 class="footer-heading mb-4">Компания</h2>
                <ul class="list-unstyled">
                  <li><a href="{% url 'services:index' %}">Услуги</a></li>
                  <li><a href="{% url 'main:price' %}">Прайс</a></li>
                  <li><a href="#">Сертификат</a></li>
                  <li><a href="{% url 'main:about' %}">О нас</a></li>
                  <li><a href="#">Статьи</a></li>
                  <li><a href="#">Контакты</a></li>
                </ul>
              </div>

            </div>
          </div>
          <div class="col-md-4 ml-auto">

            <div class="mb-5">
              <h2 class="footer-heading mb-4">Подпишитесь на обновления</h2>
              <form id="subscribe-form" method="post" class="footer-suscribe-form">
                  {% csrf_token %}
                  <div class="input-group mb-3">
                      <input type="email" id="email-input" name="email" class="form-control rounded-0 border-secondary text-white bg-transparent" placeholder="Введите Email" aria-label="Enter Email" required>
                      <div class="input-group-append">
                          <button class="btn btn-primary text-white" type="submit" id="button-addon2">Подписаться</button>
                      </div>
                  </div>
              </form>
              <p id="subscribe-message" style="display:none; color:white;"></p>
          </div>
          
          <script>
          document.getElementById("subscribe-form").addEventListener("submit", function(event) {
              event.preventDefault();
          
              let emailInput = document.getElementById("email-input");
              let messageElement = document.getElementById("subscribe-message");
          
              fetch("{% url 'newsletter:subscribe' %}", {
                  method: "POST",
                  headers: {
                      "X-CSRFToken": "{{ csrf_token }}",
                      "Content-Type": "application/x-www-form-urlencoded",
                  },
                  body: "email=" + encodeURIComponent(emailInput.value),
              })
              .then(response => response.json())
              .then(data => {
                  messageElement.innerText = data.message;
                  messageElement.style.display = "block";
                  messageElement.style.color = "green";  // Зеленый цвет успешного уведомления
                  emailInput.value = "";  // Очистка поля ввода после подписки
              })
              .catch(error => {
                  messageElement.innerText = "Ошибка подписки!";
                  messageElement.style.color = "red";
                  messageElement.style.display = "block";
              });
          });
          </script>
          

            <h2 class="footer-heading mb-4">Следите за нами</h2>
            <a href="#about-section" class="smoothscroll pl-0 pr-3"><span class="icon-facebook"></span></a>
            <a href="#" class="pl-3 pr-3"><span class="icon-twitter"></span></a>
            <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
            <a href="#" class="pl-3 pr-3"><span class="icon-linkedin"></span></a>
            </form>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <div class="pt-5">
              <p class="small">
            </p>
            </div>
          </div>

        </div>
      </div>
    </footer>

    </div>

    <script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "js/popper.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/owl.carousel.min.js" %}"></script>
    <script src="{% static "js/jquery.sticky.js" %}"></script>
    <script src="{% static "js/jquery.waypoints.min.js" %}"></script>
    <script src="{% static "js/jquery.animateNumber.min.js" %}"></script>
    <script src="{% static "js/jquery.fancybox.min.js" %}"></script>
    <script src="{% static "js/jquery.easing.1.3.js" %}"></script>
    <script src="{% static "js/aos.js" %}"></script>

    <script src="{% static "js/main.js" %}"></script>

    {% block extrajs %}
      
    {% endblock extrajs %}

  </body>

</html>